### ISSUE TITLE
concave_hull returns nonsense results for simple polygons

### ISSUE THREAD

**Issue by wlinna** [georust/geo#1124]
I'm testing concave_hull with a  simple polygon, and concave_hull returns very weird results. Here are the screenshots

Original polygon
![OriginalPolygon](https://github.com/georust/geo/assets/1473454/882b8dcb-911c-4d62-a3c7-fec73bde6b12)

Concave hull
![FailedConcaveHull](https://github.com/georust/geo/assets/1473454/3307ce7e-a53a-43d9-9678-e6a668859c13)

Here's the test code
```
       let exterior = LineString(vec![
            Coord { x: 5.1734996, y: 1.4128553 },
            Coord { x: 5.1734996, y: 1.5378553 },
            Coord { x: -4.9266067, y: 1.5378562 },
            Coord { x: -4.9266057, y: -8.45025 },
            Coord { x: -4.8016057, y: -8.45025 },
            Coord { x: -4.8016057, y: 1.4128553 },
            Coord { x: 5.1734996, y: 1.4128553 },
        ]);
    
        let polygon = Polygon::new(exterior.clone(), vec![]);
        let hull = polygon.concave_hull(0.5); // Whether the concavity is 0.5 or 4.0 doesn't seem to matter
```

I'm using `geo 0.27.0` with Rustc 1.72

**Comment by wlinna** [comment]
I tried this again with both  `geo 0.27` and `geo 0.28` , and it looks like nothing changed with concave hull itself. Both versions result in  following coordinates

-4.9266057 -8.45025
-4.8016057 -8.45025
5.1734996 1.4128553
5.1734996 1.5378553
-4.9266067 1.5378562
-4.9266057 -8.45025

However, I'm not sure anymore how I produced the original 3D model of the concave hull. When I generate it now, it looks like this

![imagen](https://github.com/georust/geo/assets/1473454/1575ddbc-f819-4570-9e65-1fd7a6016af6)

I checked the printed coordinates visually one by one, and they correspond with the generated triangle mesh.

So at least the algorithm produces a convex hull. But I can't make it produce the original shape.

**Comment by kirillolenev-dm** [comment]
Any updates about that? I have a similar experience when `concave_hull` provides something not close to from expected result, `concavity` param doesn't change much.

**Comment by michaelkirk** [comment]
@kirillolenev-dm - can you provide a minimal reproduction? 

e.g. the input you gave and the output you're expecting?

concave hull is a bit tricky because there's no rigorous definition for what the "correct" output should be. I'll say that @wlinna's [first screenshot](https://github.com/georust/geo/issues/1124#issue-2033842683) looks very concerning, not a hull at all, but seemingly that output can no longer be reproduced. 

The [second one](https://github.com/georust/geo/issues/1124#issuecomment-2081122898) at least looks like a hull, but admittedly doesn't look very concave.

I don't use these methods myself, but I'd be willing to look into any issues with it if you can gather more expected input/outputs.

**Comment by michaelkirk** [comment]
(sorry that this sat here so long!)

**Comment by wlinna** [comment]
I suppose I could turn my example into an actual unit test, but that is not much.
Maybe I could create some synthetic inputs / outputs.

**Comment by wlinna** [comment]
Hello @michaelkirk , I made a unit test out of the original case. Please tell me what you think of it.   I can make another, synthetic and simplified test based on a real case I would like to use concave hull on.

```
    #[test]
    fn concave_hull() { // https://github.com/georust/geo/issues/1124
        
        let line_string = LineString(vec![
            Coord { x: 5.1734996, y: 1.4128553 },
            Coord { x: 5.1734996, y: 1.5378553 },
            Coord { x: -4.9266067, y: 1.5378562 },
            Coord { x: -4.9266057, y: -8.45025 },
            Coord { x: -4.8016057, y: -8.45025 },
            Coord { x: -4.8016057, y: 1.4128553 },
            Coord { x: 5.1734996, y: 1.4128553 },
        ]);

        // get_rr().log("2d/exterior_point", 
        // &Points2D::new(line_string.coords().map(|c| [c.x, c.y]))
        // ).ok();

        let indices_not_on_convex_hull = [5];

        let indices_on_convex_hull = (0..line_string.coords_iter().count())
            .filter(|i| !indices_not_on_convex_hull.contains(i))
            .collect::<Vec<_>>();

        let coords_on_convex_hull = indices_on_convex_hull
            .iter()
            .map(|i| line_string.0[*i])
            .collect::<Vec<_>>();
    
        let polygon = Polygon::new(line_string.clone(), vec![]);
        let hull = polygon.concave_hull(2.0); // Whether the concavity is 0.5 or 4.0 doesn't seem to matter

        // Concave hull should include all the coords that a convex hull would
        for coord_on_convex_hull in &coords_on_convex_hull {
            assert!(hull.exterior().contains(coord_on_convex_hull));
        }

        // This line jumps takes a huge leap from one coord on a convex hull to another.
        let bad_line = geo::Line::new(line_string[4], line_string[6]);
        let bad_line_inv = geo::Line::new(line_string[6], line_string[4]);

        for line in hull.lines_iter() {
            assert_ne!(line, bad_line);
            assert_ne!(line, bad_line_inv);
        }

        // get_rr().flush_blocking();
    }
```

**Comment by michaelkirk** [comment]
That's a good example, thanks!
It's intuitively surprising to me that the output of concave hull would be so convex.

In fact, in your case I notice that the `polygon.convex_hull() == polygon.concave_hull(2.)` which is maybe interesting.

I'm not following all the specifics of your test case - one thing in particular:
```
// Concave hull should include all the coords that a convex hull would
for coord_on_convex_hull in &coords_on_convex_hull {
    // hull.exterior() is a LineString — it's `contains` semantics are 1-dimensional.
    // I think you want `hull.contains(coord_on_convex_hull)`
    assert!(hull.exterior().contains(coord_on_convex_hull));
}
```

**Comment by wlinna** [comment]
> I'm not following all the specifics of your test case - one thing in particular:

```rust
// Concave hull should include all the coords that a convex hull would
for coord_on_convex_hull in &coords_on_convex_hull {
    assert!(hull.exterior().contains(coord_on_convex_hull));
}
```

I know linestring semantics are 1-dimensional, and that's why I'm using that specifically.
The way I understand it, concave hull of a shape must contain all the same points as its convex hull plus some other points that add concavity to the hull.

Now, I'm not sure if my `Linestring::contains`-based is too sensitive to floating point errors, but my gut feeling was that the points on a convex hull would be "found" (which does not lose precision) and not "computed" (which would lose precision).


I'm not sure `hull.contains(coord_on_convex_hull)` is a correct check to make. To quote `DE-9IM` from wikipedia, contains is explained like this:

> "a contains b [iff](https://en.wikipedia.org/wiki/If_and_only_if) no points of b lie in the exterior of a, and at least one point of the interior of b lies in the interior of a"

Doesn't this mean that ` hull.contains(coord_on_convex_hull)` would have to be `false`?

**Comment by michaelkirk** [comment]
Sorry, I didn't understand that you were trying to inspect the **boundary** of the hulls, so I gave bad advice. Please ignore me.

**Comment by michaelkirk** [comment]
I believe this is resolved by #1442 (in the upcoming geo release)

**Comment by wlinna** [comment]
Actually, the test still fails; the problem hasn't gone anywhere. To make sure this is not about the assertions, I rendered the triangle again and the diagonal line is still there.

I use geo 0.32

**Comment by wlinna** [comment]
Actually the concave hull looks worse now:

<img width="717" height="667" alt="Image" src="https://github.com/user-attachments/assets/5c49f19e-6386-42d0-8e4b-522de4c9ea82" />

Notice the weird bottom-left corner

**Comment by michaelkirk** [comment]
Well, that is technically a concave hull - it appears to contain all the original vertices, while taking up less area. 

I agree that intuitively it seems like not a very good one in this case. @wwaltersdavis do you have any ideas?

One thing I noticed while debugging:


### input

```rust
let input = wkt!(POLYGON((5.1734996 1.4128553,5.1734996 1.5378553,-4.9266067 1.5378562,-4.9266057 -8.45025,-4.8016057 -8.45025,-4.8016057 1.4128553,5.1734996 1.4128553)));
```

<img width="464" height="442" alt="Image" src="https://github.com/user-attachments/assets/c94b322e-85ce-4c82-8517-0638505bb702" />

### output

```rust

// concavity 2.0 (default)
// POLYGON((-4.9266057 -8.45025,-4.8016057 -8.45025,5.1734996 1.4128553,5.1734996 1.5378553,-4.8016057 1.4128553,-4.9266067 1.5378562,-4.9266057 -8.45025))
dbg!(polygon.concave_hull_with_options(ConcaveHullOptions::default().concavity(2.0)));

// concavity 8.0 (same results as 2.0)
// POLYGON((-4.9266057 -8.45025,-4.8016057 -8.45025,5.1734996 1.4128553,5.1734996 1.5378553,-4.8016057 1.4128553,-4.9266067 1.5378562,-4.9266057 -8.45025))
dbg!(polygon.concave_hull_with_options(ConcaveHullOptions::default().concavity(8.0)));
```
<img width="445" height="440" alt="Image" src="https://github.com/user-attachments/assets/3c6f60ea-205a-4ff9-a386-c1ff53a61192" />

---

Interestingly, if I ratchet concavity up to 1,000 I get something that looks like the convex hull.

```rust
// concavity 1000.0
// POLYGON((-4.9266057 -8.45025,-4.8016057 -8.45025,5.1734996 1.4128553,5.1734996 1.5378553,-4.9266067 1.5378562,-4.9266057 -8.45025))
dbg!(polygon.concave_hull_with_options(ConcaveHullOptions::default().concavity(1000.0)));
```

<img width="478" height="454" alt="Image" src="https://github.com/user-attachments/assets/91844092-6354-4516-babd-f823a051b2ff" />

---

To be clear, I'm expecting the output concave hull, especially one with high concavity to look something closer to the input, which is already quite concave.

Are you surprised by this output @wwaltersdavis?

**Comment by wwaltersdavis** [comment]
Thanks @michaelkirk for flagging this!

Yes this is the expected result.

One thing to note is that a lower `concavity` parameter produces a more concave shape. (This is inline with mapbox's concaveman but intuitively I would agree that a higher concavity should result in a more concave hull, something which could be addressed).

Using the example given with `concavity(1.0)` now does provide the desired result and running the [test above](https://github.com/georust/geo/issues/1124#issuecomment-2613856831) with 1.0 also passes.

```rust
// rust 1.92.0, geo 0.32.0
// concavity 1.0
let polygon = wkt!(POLYGON((5.1734996 1.4128553,5.1734996 1.5378553,-4.9266067 1.5378562,-4.9266057 -8.45025,-4.8016057 -8.45025,-4.8016057 1.4128553,5.1734996 1.4128553)));

dbg!(polygon.concave_hull_with_options(ConcaveHullOptions::default().concavity(1.0)));
```

<img width="450" height="450" alt="Image" src="https://github.com/user-attachments/assets/e5010c84-db85-4af1-b88f-06d13da0672e" />

---
Though the above example produces the expected output, with the concaveman method this may not always be the case. 
For example, using the same shape rotated around it's centroid 180 degrees will produce a concave hull similar to the example [here](https://github.com/georust/geo/issues/1124#issuecomment-3683966204) as seen below:

```rust
// concavity 1.0
let polygon = wkt!(POLYGON((5.1734996 1.4128553,5.1734996 1.5378553,-4.9266067 1.5378562,-4.9266057 -8.45025,-4.8016057 -8.45025,-4.8016057 1.4128553,5.1734996 1.4128553)));
let rotated = polygon.rotate_around_center(180.0);

dbg!(rotated.concave_hull_with_options(ConcaveHullOptions::default().concavity(1.0)));
```

<img width="450" height="450" alt="Image" src="https://github.com/user-attachments/assets/7989e526-88fc-46e3-ac23-9d424da8c83a" />

### Cause of unexpected results
Three key parts of the concaveman approach drive these results
1. It is a points based approach and requires a polygon to be converted into its constituent vertices, before a hull is calculated around these vertices
1. It iterates through hull edges in order and "drills" inwards if the concavity criteria are met
1. Each point can only be used once

Together these mean that a desired result of a hull wrapping around an input polygon will not always be found.

This indicates the issue is maybe now less about the [nonsense results as initially reported](https://github.com/georust/geo/issues/1124#issue-2033842683) but more the issue of concave hulls not respecting interior geometries and returning undesried results and having potentially misleading implementations for more complex geometries.

---

I was looking at a solution for this last year and keen to pick this up again soon as do have a [working prototype solution](https://github.com/wwaltersdavis/geo/blob/99715743ab62643a81ce0014b0c92fe444b68963/geo/src/algorithm/concave_hull.rs#L143) which addresses this as well as an implementation of concave hulls for `GeometryCollections` and have added this example as a [unit test](https://github.com/wwaltersdavis/geo/blob/99715743ab62643a81ce0014b0c92fe444b68963/geo/src/algorithm/concave_hull.rs#L967).
